services:
  filejet.http_client:
    class: FileJet\HttpClient

  filejet.mutation:
    class: FileJet\Mutation

  filejet.config:
    class: FileJet\Config
    arguments:
      - "%filejet.api_key%"
      - "%filejet.storage_id%"
      - "%filejet.signature_secret%"
      - "%filejet.auto_mode%"
      - "%filejet.base_url%"
      - "%filejet.custom_domain%"

  filejet.filejet:
    class: FileJet\FileJet
    arguments:
      - '@filejet.http_client'
      - '@filejet.config'
      - '@filejet.mutation'


  filejet.extension:
    class: FileJetBundle\Twig\FileJetExtension
    arguments:
      - '@filejet.filejet'
      - '@filejet.config'
    tags:
      - { name: "twig.extension" }
