services:
  _defaults:
    autowire: true
    autoconfigure: true

  FileJet\HttpClient: ~
  FileJet\Mutation: ~

  FileJet\Config:
    arguments:
      - "%filejet.lambda_controller_function_name%"
      - "%filejet.custom_domain%"
      - "%filejet.signature_secret%"
      - "%filejet.auto_mode%"
      - "%filejet.base_url%"

  FileJet\FileJet:
    arguments:
      - '@FileJet\HttpClient'
      - '@FileJet\Config'
      - '@FileJet\Mutation'
      - '@filejet.lambda_client'


  FileJetBundle\Twig\FileJetExtension:
    tags: ["twig.extension"]
