services:
  _defaults:
    autowire: true
    autoconfigure: true

  FileJet\HttpClient: ~
  FileJet\Mutation: ~

  FileJet\Config:
    arguments:
      - "%filejet.api_key%"
      - "%filejet.storage_id%"
      - "%filejet.base_url%"
      - "%filejet.signature_secret%"
      - "%filejet.auto_mode%"

  FileJet\FileJet:
    arguments:
      - '@FileJet\HttpClient'
      - '@FileJet\Config'
      - '@FileJet\Mutation'


  FileJetBundle\Twig\FileJetExtension:
    tags: ["twig.extension"]
